### ISSUE TITLE
geth import could fail for unknown reason

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/shadow#103]
<img width="1472" alt="04E891DA-EA12-4973-9B99-86BFBDD76A1C" src="https://user-images.githubusercontent.com/1070122/97992823-30b5b900-1e1e-11eb-99ed-db9e3153d9f3.png">

**Comment by xiaoch05** [comment]
I guess the reason is that the ethereum node is syncing, and the 8902396 block is unavailable.
I add some logs and give a simulation test, then get the same error. (the ethereum node has only 6250 blocks)

<img width="955" alt="4DB9C1DD-D73F-40C6-8BB9-A9DB8A627691" src="https://user-images.githubusercontent.com/15799431/98224010-e3585980-1f8d-11eb-9c4e-bc3b0a65a0e5.png">

<img width="700" alt="23AFD326-699F-42C5-960D-7EC1FB3CD9B9" src="https://user-images.githubusercontent.com/15799431/98224094-0551dc00-1f8e-11eb-85bd-ce0065678f76.png">
